# Generated by Django 5.1.2 on 2024-10-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50,
                 unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('thumbnail', models.ImageField(
                    upload_to='thumbnails/', verbose_name='Thumbnail')),
                ('slug', models.SlugField(unique=True)),
                ('published_at', models.DateTimeField(
                    editable=False, null=True, verbose_name='Published at')),
                ('is_published', models.BooleanField(
                    default=False, verbose_name='Published')),
                ('num_likes', models.IntegerField(
                    default=0, editable=False, verbose_name='Likes')),
                ('num_views', models.IntegerField(
                    default=0, editable=False, verbose_name='Views')),
                ('tags', models.ManyToManyField(
                    related_name='videos', to='core.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
