# Generated by Django 5.1.2 on 2024-10-28 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='videos', to='core.tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='VideoMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UPLOAD_STARTED', 'Upload Started'), ('PROCESSING_STARTED', 'Processing Started'), ('UPLOAD_FINISHED', 'Processing Finished'), ('UPLOAD_ERROR', 'Processing Error')], default='UPLOAD_STARTED', max_length=20, verbose_name='Status')),
                ('path', models.CharField(max_length=255, verbose_name='Video Path')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='video', to='core.video', verbose_name='Media')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
